id: redirect_unauthorized_user
learningObjectives:
  - Handling unauthorized requests
hints:
  - On the front end, create a new function that cheks if the user is logged in and if not redirect them to the login screen.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: For the last part, let's change the flow for un-authorized requests.
          - text: Instead of leaving them in oblivion, let's redirect them to the /login page.
          - text: Remember, we’re here to build a smooth user journey!
          - text: Let's start by having the user settings page at /settings to redirect to the login page if they are **not logged in**.
          - text: :instruction[Change the code and tag me on the PR so I’ll be able to review it ASAP].


trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: lucca
                message: "Reviewing this right now, let's see..."
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Got your PR, going over it right now."
                    delay: 100
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Make sure your fix passes all the checks, then try again please."
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: lucca
                message: "Looks like this code change didn't work. Can you take a second look?"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Nice job, go ahead and merge this PR."
                    delay: 2000
            - actionId: github_pr_approve
              params:
                person: lucca
                message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_merged:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "Seems that we are done here. Thanks for your help!"
                    delay: 1500
            - actionId: finish_step
githubActions:
  backend:
  frontend:
    capabilities:
      - jest-puppeteer
    testFile: "redirect_unauthorized.test.js"
